;;; geiser-godot-s7-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "geiser-godot-s7" "geiser-godot-s7.el" (0 0
;;;;;;  0 0))
;;; Generated autoloads from geiser-godot-s7.el

(autoload 'connect-to-godot-s7 "geiser-godot-s7" "\
Start a Godot s7 REPL connected to a remote process.

Start a Scheme Repl in the active Godot s7 scene." t)

(geiser-activate-implementation 'godot-s7)

(autoload 'run-godot-s7 "geiser-godot-s7" "\
Start a Geiser Godot s7 REPL." t)

(autoload 'switch-to-godot-s7 "geiser-godot-s7" "\
Start a Geiser Godot s7 REPL, or switch to a running one." t)

(register-definition-prefixes "geiser-godot-s7" '("geiser-godot-s7-" "godot-s7"))

;;;***

;;; End of scraped data

(provide 'geiser-godot-s7-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-godot-s7-autoloads.el ends here
